### ISSUE TITLE
data screening/ cleanup

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ERL-review#25]
**check outlier / suspicious values:**
- [x] `Heshan Hilly Land   Interdisciplinary Experimental Station | Aggrading Eucalyptus urophylla Forest. Stand   established around 2004` (NEP outlier)
- [x] `Haw River | Aggrading Temperate Evergreen Forest. Stand   established around 1958.5` (NEP outlier)
- [x]  Arevalo_2011_luce research site in Alberta Canada
- [x] Gainesville
- [x] Turkey Point sites
- [x] additional high Bond-Lamberty NEP values... **--> these values are correct**
- [x] SRDB biomass values (see [below](https://github.com/forc-db/ERL-review/issues/25#issuecomment-694814798))
- [x] deadwood standing outlier (see [below](https://github.com/forc-db/ERL-review/issues/25#issuecomment-694930533))
- [x] deadwood down outlier (see [below](https://github.com/forc-db/ERL-review/issues/25#issuecomment-694932777))
- [x] fine root biomass outliers from SRDB ([here](https://github.com/forc-db/ERL-review/issues/25#issuecomment-694935361))

**check/  merge duplicates**
- [x] `Caxiuana~ National   Forest Reserve | Aggrading Tropical Evergreen Forest. Stand   established around 1960`. This has NEE record. (discussed [here](https://github.com/forc-db/ERL-review/issues/25#issuecomment-694334293))
